### ISSUE TITLE
Applications section in docs

### ISSUE THREAD

**Issue by lugubris** [void-linux/void-docs#116]
Will there be an applications section? For example docs for getmail, mpv and other applications?

Something like -> https://wiki.voidlinux.org/Applications

**Comment by HadetTheUndying** [comment]
I'd be willing to contribute a lot to this but the console output on a lot of programs that require additional manual configuration is mostly adequate. Maybe we need to look and see what needs additional documentation though. Steam is definitely something that comes to mind, though it does have console output about multilib.

**Comment by Wychmire** [comment]
Having an applications section would provide a section for things like Steam and Lutris's dependencies, which is one of a few things keeping me from skipping the wiki entirely.

I do think that anything that'd be included in the docs should available in the repos, vs the wiki having several entries that are only flatpaked (flatpak'd? flatpaks?).

**Comment by bobertlo** [comment]
IMO an applications section with a list of general Linux applications, as well as information on how to use those applications (not specific to Void Linux) is outside the scope of this project.

That said, I do think things like a list of common dependencies for Steam are a reasonable inclusion somewhere in the docs, but others had different views on that last time it came up. I don't see a need for an entire section on these topics though.

**Comment by Wychmire** [comment]
Maybe more of an "Application Issues" section? That way there wouldn't be a need to replicate everything on the Arch Wiki's [Applications page](https://wiki.archlinux.org/index.php/List_of_applications), and there'd be an area for void-specific fixes and dependencies for things like Steam

**Comment by lugubris** [comment]
Arch Wiki is good but I guess only users of archlinux are expected to be able to edit it because on signup it asks for base32 encode of a pacman command's output, also looks like the activity is a lot less nowadays. Only issue I see with having an applications section is it getting outdated, to solve that we can do what we do with packages - assign maintainers to docs pages.

So say I volunteer to maintain `getmail` page (not up-to-date on archwiki) then its my responsibility to keep it up-to-date. There could be "last updated/ revised on" date on pages so readers know that the information may be out of date.

**Comment by Chocimier** [comment]
Void specifics could be documented and installed with package. https://github.com/void-linux/void-packages/pull/20735

Then docs could have single section pointing to /usr/share/doc/${pkgname}/README.voidlinux .

**Comment by bobertlo** [comment]
#188 has more discussion related to this. We have repeatedly discussed the scope of the documentation, and how it does not cover general use of other applications. The ideas proposed in that issue should be sufficient, given the stated goals of this project.

I am going to close this now. Any discussion of @Chocimier s idea can happen in that PR.
