### ISSUE TITLE
Document default groups

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-docs#121]
This came  up yesterday in the IRC channel, there are a number of [default groups](https://github.com/void-linux/void-packages/blob/master/srcpkgs/base-files/files/group) that void ships with that are currently not really documented.

I think a section in the docs that describes what each group does would be good to have.

**Comment by flexibeast** [comment]
i'd like to work on this. Whereabouts in the Handbook should this new section be added?

**Comment by Duncaen** [comment]
I think "Configuration > Users & Groups" and then maybe a "Default Groups" or just as section in the "Users & Groups" page.
I think it only makes sense to split this into its own page if the "Users & Groups" page would get too long.

I do think we were too eager to split sections like "Repositories" and some other categories into too many sub pages, which really doesn't help readability.

**Comment by bobertlo** [comment]
Closed by #155
