### ISSUE TITLE
Section about date/time and ntp daemons

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-docs#123]

**Comment by flexibeast** [comment]
i'd like to work on this. i presume this would go in the 'Services and Daemons' section of the Handbook? What sort of information should be included?

**Comment by nilium** [comment]
For NTP daemons, probably just very basic setup of the main NTP daemons (chrony, openntp, and ntpd). Specifically, package names and services to link. Don't think any of them require additional configuration. It wouldn't have to go into detail on more advanced usage, given that both have their own documentation.

Date/time is pretty broad, so I'm assuming the intent is to just cover how to set it, if one wanted to, and keep it synchronized with the daemons.

**Comment by flexibeast** [comment]
With the merging of #132, can this now be closed?

**Comment by Duncaen** [comment]
I feel like we are still missing something about rc.conf `HARDWARECLOCK` and timezones.

**Comment by zenny** [comment]
> I think we are still missing something about rc.conf `HARDWARECLOCK` and timezones.

@Duncaen I guess so, too because the time shown is incorrect until ntp servers are used. Even after ntp servers deployed with correct `HARDWARECLOCK` and `TIMEZONE` in rc.conf, the time displayed is 5 minutes ahead of any other atomic clocks (like smartphones)!

**Comment by flexibeast** [comment]
@zenny: My understanding is that if the hardware clock has drifted too far from the time reported by time servers, one needs to use something like `ntpdate` to set the hardware time; the ntp servers can then maintain the clock from there.

@Duncaen: If what i wrote above is correct, should this information be added to the Handbook?

**Comment by bobertlo** [comment]
I think with the addition of https://github.com/void-linux/void-docs/pull/154 covers the last issue.

I just saw that these are duplicated between `Date & Time` and `rc files`, but that is a separate issue. I'm closing this.
