### ISSUE TITLE
Base system requirements says EM64T (ie. Intel) CPU required for 64-bit.

### ISSUE THREAD

**Issue by jrigg** [void-linux/void-docs#128]
Base system requirements doc is either misleading or lacking information. It says EM64T CPU is required for 64-bit, but that's Intel only and implies that AMD CPUs are not supported. This needs clarification.

**Comment by leahneukirchen** [comment]
I recommend using `x86_64` instead.

**Comment by bobertlo** [comment]
Closed by cbb131c5d656dc499e7fcd6aca8dd815b2074514
