### ISSUE TITLE
Document intel-ucode and other firmware packages

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-docs#129]

**Comment by bobertlo** [comment]
Can this be closed?

**Comment by ericonr** [comment]
@Duncaen can we close this one? Or is there something we still need to include?

**Comment by Duncaen** [comment]
I think it would be good to make a firmware section and move the microcode stuff into it.
There are a few other firmware packages that are not installed by default and I think because the question in how to get rid of firmware packages installed by default it would make sense to add a paragraph about that and link to `ignorepkg` documentation for xbps.

**Comment by flexibeast** [comment]
#368 merged. Closing.
