### ISSUE TITLE
Add 'Musl' section?

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#130]
Might it be useful to port [the Musl page on the wiki](https://wiki.voidlinux.org/Musl) (or at least some of it) across to the Handbook, and mention things like the `gcompat` package?

**Comment by rubyFeedback** [comment]
This would be pretty cool. I have been searching for an oldschool veteran *nix distribution and musl in combination with busybox, and perhaps llvm for a small core system would be very interesting to me - so any documentation here is very useful. I did succeed in building/compiling a custom musl-toolchain and it works too, but past this point I am a bit lost, as in ... "what to do next". So I am missing some steps.

Thus, this would be very useful in general - any documentation improvement here.

**Comment by bobertlo** [comment]
@rubyFeedback some of those topics seem outside the scope of this documentation. You may want to take a look at alpine linux for a busybox musl system. There are good sources on the musl wiki for examples of other toolchains as well. Also, the void bootstrap toolchain. Linux From Scratch is also a great guide for these off topic ideas. IIRC they now even have a musl based guide?

**Comment by flexibeast** [comment]
i'm starting work on this.

**Comment by bobertlo** [comment]
closed by #163
