### ISSUE TITLE
Extend guide about NetworkManager

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-docs#135]
Please extend guide about NetworkManager in [docs](https://docs.voidlinux.org/config/network/networkmanager.html) with the info from "Wireless (NetworkManager, no window manager present)" from [wiki](https://wiki.voidlinux.org/Network_Configuration).

* Add info that you need to create file `/etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules`.
* Add info that permission must be at least 644: `chmod 644 /etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules` (missing in the wiki).
* Add info that user should be in `network` group.

I was installing fresh void installation on my laptop and spent a lot of time debugging this issue. I kept getting errors that user is not authorized to manage network connections.

**Comment by flexibeast** [comment]
Hmm, my initial thought on this is that, whilst the third point should certainly be included in the docs, the first and second points should be addressed in the `NetworkManager` package, rather than having the docs describe a workaround. @bobertlo, @ericonr, thoughts?

**Comment by kotoko** [comment]
Wiki seems to down to me. Just to avoid confusion this is the content of file `50-org.freedesktop.NetworkManager.rules` that was on the wiki earlier:
```
polkit.addRule(function(action, subject) {
	if (action.id.indexOf("org.freedesktop.NetworkManager.") == 0 && subject.isInGroup("network")) {
		return polkit.Result.YES;
	}
});
```

**Comment by ericonr** [comment]
@kotoko no worries, the wiki came back :D

@flexibeast polkit rules are definitely packaging issues. And it seems the package already contains at least a `/usr/share/polkit-1/actions/` file. I think this should be an issue over at void-packages instead.

**Comment by flexibeast** [comment]
i've merged https://github.com/void-linux/void-docs/pull/221 about NM users needing to be part of the `network` group, and have opened https://github.com/void-linux/void-packages/issues/21578 re. the polkit rules.

**Comment by flexibeast** [comment]
https://github.com/void-linux/void-packages/issues/21578 has now been closed by https://github.com/void-linux/void-packages/pull/21608, so i'm closing this issue.
