### ISSUE TITLE
Undocumented /etc/rc.conf

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-docs#148]
The void handbook lacks information about `/etc/rc.conf`, `/etc/rc.local` and `/etc/rc.shutdown`.

I assume this is so because english/american keyboards don't need additional tweaks... but it's really important in all other cases.

Please document them properly!

**Comment by flexibeast** [comment]
i'd like to work on this. Would you like an overview of the purpose of each of these files, mentioning that `rc.conf` in sourced in stage 1 and stage 3, `rc.local` in stage 2, and `rc.shutdown` in stage 3? 

> I assume this is so because english/american keyboards don't need additional tweaks... but it's really important in all other cases.

So the description of `rc.conf` should mention setting KEYMAP? Would you like other variables mentioned as well, e.g. FONT?

**Comment by xtraeme** [comment]
Yes, all variables should be documented.

**Comment by bobertlo** [comment]
Closed by #154
