### ISSUE TITLE
connman is insecure, please consider removal

### ISSUE THREAD

**Issue by Tcll** [void-linux/void-docs#153]
with a quick look at wireshark upon connecting to the internet
connman updates connection stats over HTTP to ipv4.connman.net using GET requests

I'm not sure if this is a local server or what (traffic was only sent when ethernet was connected)
but anything that uses web technology is insecure and prone to WAN hacking

after a bit of research, it appears connman is Intel technology, so yeah, wouldn't be surprised if it's found Intel is actually spying.
(wouldn't be the first time they've done so)

also, while I do highly recommend removal from the docs, I also recommend removal from the repos.
normally I wouldn't go this far and recommend as such, since I support FOSS and ~OSI,
but there's at least 2 things against connman that make me consider otherwise:
- if the TCP/HTTP connections are indeed spying, then connman is a virus.
- web technologies don't adhere to the security attitude of BSD and are purely preferential.

I was goaded into the lightweightedness of connman from the docs which is why I installed.
(it's only a 32bit machine with 2GB of RAM)

if I had to recommend a replacement, network-admin seems much more viable:
![](https://user-images.githubusercontent.com/773959/76082527-a0b32d00-5f79-11ea-86f5-473c2a389f09.png)
if there's anything wrong with this though, I'll happily retract this recommendation ;)

**Comment by xtraeme** [comment]
Saying that connman is spyware seems to be a bit agressive to me.

Are you sure it's doing something malicious? if true, can you provide details?

If you have detailed data I'll take a look at it.

**Comment by Duncaen** [comment]
This doesn't make it insecure. There is an option to disable this behaviour.

**Comment by xtraeme** [comment]
pointed out by @Duncaen 

https://git.kernel.org/pub/scm/network/connman/connman.git/tree/README#n397

So that it's documented and upstream provides a good explanation and a way to disable it.

If you don't like this option, disable it.

Not an issue.

**Comment by Tcll** [comment]
well that answered my question I was about to ask, thanks. :+1: 

I'm trying to harden my system against WAN attacks, and this took me by surprise.

**Comment by eli-schwartz** [comment]
Try asking upstream to make this configurable, similar to NetworkManager: https://wiki.archlinux.org/index.php/NetworkManager#Checking_connectivity

It seems reasonable to allow users to specify their own endpoint providing the `X-ConnMan-Status: online` check.
