### ISSUE TITLE
Should there be an applications section?

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-docs#167]
I am looking to port this page over from the wiki https://wiki.voidlinux.org/Applications
but I am not sure where to put it. Should there be an applications section?

**Comment by flexibeast** [comment]
Personally, i don't think there should be an 'Applications' section in the Handbook. There are *many* applications in the repos, with new applications being added (and other applications being removed) on a regular basis, and i don't think it's particularly useful to try to maintain a manual list of such software. If people want to find out what applications are available for a particular purpose on Linux, they can do Web searches, then check if the software they want is already in the repos, submitting a package request if not.

**Comment by bobertlo** [comment]
There has been discussion in the past. People have different opinions on this, but it has been more or less decided that it does not belong in *this* document.

**Comment by andinus** [comment]
Refer to #116

**Comment by Frick-David** [comment]
Okay, Thanks. Closing Issue!
