### ISSUE TITLE
Invalid sha256 urls

### ISSUE THREAD

**Issue by j0ack** [void-linux/void-docs#172]
The doc mentioned that sha256 for images is available at 

`http://alpha.de.repo.voidlinux.org/live/current/sha256sums.txt`

But the files are named respectively sha256.txt and sha256.sig now. I don't know if the doc must be updated or the file renamed on the server.

**Comment by bobertlo** [comment]
IIRC this is happened when new keys were used?

Either way the docs should point to the correct location. If they are decided to move on the servers we can once again change the docs.
