### ISSUE TITLE
GNOME setup from base install needs documentation

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-docs#174]
Following the wiki, installing gnome and enabling the gdm service does not work. I have been able to figure it out, but not document the process. You definitely need to also install xorg and xinit. Also I think elogind is required?

The main issue is that if you don't have everything right and start gdm it locks up. I have been adding gnome-session to my xinitrc and making sure it works, then gdm seems to be able to work? I also would `touch /etc/sv/gdm/down` and `sv once gdm` to test before getting things to work for sure.

I need to do more VM testing before trying to write up anything, but I think this would be useful information. We don't want people "breaking" their systems.

**Comment by flexibeast** [comment]
> Also I think elogind is required?

That's my understanding. From [the elogind README](https://github.com/elogind/elogind/blob/master/README.md):

> [T]o run GNOME these days means that you need to have support for the login1 D-Bus interface, which is currently only provided by systemd. That is the origin of this project: to take the excellent logind functionality from systemd and provide it as a standalone package.

**Comment by bobertlo** [comment]
Yeah, I'll have to start up some VMs to debug this. Because it seems like just starting dbus and then starting elogind is not enough and you need to reboot? This is pretty important information for anyone who wishes to run GNOME from a manual or base install. :)

**Comment by flexibeast** [comment]
Agreed. :-)

i've just created some VMs to help work on these sorts of issues. In this particular case, we're trying to work out all the steps necessary to get GNOME working?

**Comment by bobertlo** [comment]
Great!

Right. Specifically from a fresh install. I'm thinking a reboot after the set of necessary services is sufficient, but haven't had time to check.

**Comment by flexibeast** [comment]
Okay, working on creating a GNOME section based on the wiki page.

**Comment by flexibeast** [comment]
Closing via https://github.com/void-linux/void-docs/commit/b2db298502350ed628d2fa7d6dedca9cf75365d2.
