### ISSUE TITLE
'PulseAudio' section: Tell users to add themselves to the 'pulse' group?

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#175]
The ['PulseAudio' section of the Handbook](https://docs.voidlinux.org/config/media/pulseaudio.html) states:

> There are several methods of allowing PulseAudio to access to audio devices. The simplest one is to make use of the `audio` group.

The wiki [suggests](https://wiki.voidlinux.org/PulseAudio#Without_a_session_manager) that this means adding the relevant user to the 'audio' group. Is that correct? If so, i'll open a PR to add that information.

**Comment by bobertlo** [comment]
Yeah, you could just reword this slightly if you want.
