### ISSUE TITLE
Remove "WEP configuration" from wpa_supplicant section?

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#178]
Is there any reason not to remove the "WEP configuration" subsection? As far as i'm aware, WEP is way past deprecated.

**Comment by Vaelatern** [comment]
And yet still used in random places. Python 2 is way past deprecated too.

**Comment by flexibeast** [comment]
Okay, fair enough. So can the section be reworked to first provide information about the WPA case, which i assume is the more common case?

**Comment by Vaelatern** [comment]
That sounds reasonable.

**Comment by bobertlo** [comment]
I generally just try not to touch valid information about things I don't use, but reorganizing this sounds reasonable to me.

**Comment by flexibeast** [comment]
https://github.com/void-linux/void-docs/pull/180

**Comment by flexibeast** [comment]
https://github.com/void-linux/void-docs/commit/dbe35e64fc5fd3711678b70f794805d0a7af3e12
