### ISSUE TITLE
Troubleshooting update errors

### ISSUE THREAD

**Issue by nicklaf** [void-linux/void-docs#186]
We have a section on [updating](https://docs.voidlinux.org/xbps/updating.html) Void, but no discussion on how to troubleshoot common error messages when the update fails.

For example, removing orphans with `xbps-remove -o` sometimes resolves the "unresolvable shlibs" error that occurs when attempting `xbps-install -Su`.

The old wiki has some [discussion](https://wiki.voidlinux.org/Frequently_Asked_Questions#A_.27Transaction_aborted_due_to_unresolved_shlibs.27_error_is_preventing_me_from_updating.21) about a related but different problem as well.

**Comment by bobertlo** [comment]
I think the `xbps-remove -o` case could be mentioned at the same time as importing the same error caused by the build server staging.
