### ISSUE TITLE
Make a section for "external applications"

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-docs#188]
After somewhat lengthy discussion on IRC, I'd like to record it here. The proposal is to try and make a single section (possibly even a single page) as reference for all applications that aren't installed via xbps.

This page would:

* Be "probably in the installing section, near the existing documentation for nonfree" and "with a paragraph explaining the distinction between nonfree, non-distributable, and proprietary closed-source". @the-maldridge 
* Refer to the resticted packages that can be built locally with xbps-src. It's a section that [already exists in the docs](https://docs.voidlinux.org/xbps/repositories/restricted.html). @flexibeast 
* Tell people to try and use flatpaks for most of their external needs, especially when proprietary (we might need to document flatpak too, if people have issues with it). Probably list a few applications that flatpak allow people to use. @bobertlo 
* Explain that some language package managers, such as pip and gem (#185) can require the respective devel packages for those languages (so python-devel and ruby-devel) in order to build some libraries. This can be even more relevant when using a musl build.
* If https://github.com/void-linux/void-packages/pull/20735 is accepted, include information about it and how people can use xtools to extract that single file from the package, without installing it. Perhaps even make another xtool for that? To go along with xmandoc.

What we need, AFAIK:

- [ ] write the actual page
- [ ] decide if it's going into an existing section or if it's going to be its own section
- [ ] consider moving some docs to their respective packages

I wrote this right before going to sleep, so if there are any egregious mistakes I can correct them in a bit.

**Comment by bobertlo** [comment]
It seems like this is the intention of this post, but for clarity I will state again that we are interested in a single page explaining common third party application general handling procedures, i.e. using flatpak, and we are not interested in a "section" for long pages covering each application. (i.e. steam #159)

**Comment by ericonr** [comment]
Closed! Thanks @anjandev :D
