### ISSUE TITLE
Is a consistent style desired? Should documentation be more terse?

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-docs#190]
So, usually package installation is presented as the whole `xbps-install` command, but something that the Arch wiki actually does right IMHO is just list the packages that people have to install and hyperlink the word "install" to the guide about installing packages. That feels more concise, at least to me.

This also goes for enabling services. There are instructions for enabling dbus, for example, all around the docs. Wouldn't it be better to just mention "make sure that the dbus service is enabled" and link to the services page as well? That's what the NetworkManager page does, while the IWD and Bluetooth page both have the `ln -s /etc/sv/dbus /var/service` command.

This is not a really big issue, but it would be interesting if we could define some sort of guidelines around writing docs and keep a consistent style. Whatever decision is made, I can port the current pages to that (or not, if it's deemed unnecessary).

**Comment by bobertlo** [comment]
I thought this was explicitly stated somewhere. Yes, we are specifically trying to avoid command listings like you mentioned.

**Comment by ericonr** [comment]
All right, I will get to it when I have the time :D

**Comment by flexibeast** [comment]
Yes, this is mentioned in [the Handbook Style Guide](https://docs.voidlinux.org/contributing/void-docs/style-guide.html):

> Command code-blocks should not be used to describe routine tasks documented elsewhere in this Handbook. For example, when writing documentation for the `foo` package, do not provide a command code-block stating that one should install it via `xbps-install foo`.

**Comment by bobertlo** [comment]
The idea is to provide information and avoid magic commands. In the case of `xbps-install foo` it's more just redundant, but the wiki is full of copy and paste guides and we're generally trying to avoid that. There is even a lot of content that made it into the docs that could be rewritten from 'howto guide' style to English, IMO.

**Comment by ericonr** [comment]
Do you have examples? Both as a list of pages that still need to be corrected but also as guidelines.

**Comment by bobertlo** [comment]
The Full Disk Encryption guide, for example, has parts that could use more explanation and less blocks of command line. I merged that because it was sitting for over a year and is a hot topic. I think this can wait until after the chroot guide is hammered out.

Peeking around, we seem to have done a decent job of other pages, but the pages were not as well written originally. It is more of an ongoing upkeep.

I unfortunately don't have any guidelines to offer and this is only my opinion.

**Comment by flexibeast** [comment]
@ericonr: You might find several of my recent PRs, such as [this](https://github.com/void-linux/void-docs/pull/179) and [this](https://github.com/void-linux/void-docs/pull/180), useful as a source of 'before' and 'after' examples.

**Comment by flexibeast** [comment]
@ericonr: More generally, i've been modifying the style of various pages as i work on them for other reasons (e.g. adding or clarifying information); but i also feel the style should be consistent throughout the Handbook, so if you're up to doing a "style sweep" of all pages, that would be appreciated. :-)

**Comment by ericonr** [comment]
I might take on that endeavor.
