### ISSUE TITLE
Update Request: Mirror-List

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-docs#200]
https://docs.voidlinux.org/xbps/repositories/mirrors/list.html

> http://alpha.de.repo.voidlinux.org 	EU: Germany 
Replace with Finland

> http://beta.de.repo.voidlinux.org 	EU: Germany 
Delete since it doesn't exist anymore.

**Comment by ericonr** [comment]
Isn't this one solved already? @Anachron

**Comment by the-maldridge** [comment]
I think this was stuck as a part of a bug in the site updater script.  The obsolete pages have been expunged from the server.
