### ISSUE TITLE
Document non obvious package management mechanisms

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-docs#201]
You can create a virtualpkg to install a different version of the kernel without breaking dependencies. There should be a cannonical method documented for this.

`virtualpkg=linux:linux5.6` in `/etc/xbps/newerkernel.conf?

**Comment by ericonr** [comment]
I'm highjacking this issue to include everything related to XBPS that it might not be obvious that the option even exists:

- virtualpkg
- ignorepkg (less useful, this one)
- mention vkpurge (debatable)
- ...

**Comment by flexibeast** [comment]
@ericonr: With `ignorepkg` and `virtualpkg` now mentioned in the "Advanced Usage" section, and `vkpurge` mentioned in the "Kernel" section, i'd like to close this. Any objections?

**Comment by ericonr** [comment]
No problem! Closing now.
