### ISSUE TITLE
Too many missing wiki articles

### ISSUE THREAD

**Issue by linuxpotion** [void-linux/void-docs#209]
Articles like GNOME and Plasma, among others, are not available at https://docs.voidlinux.org/

If I can help in any way I will be happy to do so. I ask for help from the community to make the documentation better and more complete in all aspects.

**Comment by flexibeast** [comment]
As background, please see [this section of the Handbook](https://docs.voidlinux.org/howtoread/index.html), in particular the first two paragraphs. That said, there is currently a WIP PR re. [setting up GNOME](https://github.com/void-linux/void-docs/issues/174); i don't know if there needs to be something similar for KDE/Plasma. @bobertlo?

Keeping in mind the Handbook section i linked to above, could you describe which other wiki pages you think should be ported?

**Comment by bobertlo** [comment]
I think testing for KDE and especially seeing if there are duplicate steps would be useful. I'm buried in work right now but do want to get gnome figured out.

**Comment by ericonr** [comment]
Regarding DE setup, do you guys think it should include display manager set up as well?

**Comment by bobertlo** [comment]
> Regarding DE setup, do you guys think it should include display manager set up as well?

I'm not an expert but I think most DEs these days roll their own session. If there appears to be a lot of overlap I think it would be appropriate to cover those topics independently of each DE.

**Comment by flexibeast** [comment]
@linuxpotion: Once https://github.com/void-linux/void-docs/pull/237, which adds a "KDE" section, is finalised, i'm going to close this; but please feel free to open new issues for other pages you think might need to be added (after checking what other things are [already being worked on](https://github.com/void-linux/void-docs/pulls).)

**Comment by flexibeast** [comment]
#237 has been merged, so i'm closing this.
