### ISSUE TITLE
Make a void-docs package

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-docs#214]
This is a bit ambitious and requires some discussion on the best way to proceed, but having a `void-docs` package available could be interesting for having access to offline documentation (without having to clone a git repo) and, more importantly, for including in the live images.

What we'd have to decide:

* How to package? Package all markdown files or convert them into some other format? Would this conversion keep them readable? How would the navigation work?
* How to version the package? When would we have new docs releases? Definitely when someone builds new live images, but only updating the package then seems bad practice.

Inspiration from this taken liberally from starting a DragonFlyBSD installation and having a README right there on the root dir.

**Comment by Vaelatern** [comment]
Oh this is a cool idea. I like it.

**Comment by travankor** [comment]
>How would the navigation work?

Good old texinfo, anyone? /s

This might be interesting https://github.com/zigalenarcic/mangl

**Comment by bobertlo** [comment]
I think this would be a good place to discuss tagging re: https://github.com/void-linux/void-packages/pull/21453

I'm fine with adding a tag right now. Or later. Open to suggestions on the format of said tag. My first thoughts would just be a simple 2020-XX-XX. Downstream package templates can do whatever they want as far as leaving room for actual versioned releases if that is decided.

**Comment by ericonr** [comment]
Hello. I believe we can get back into discussing this.

**Comment by travankor** [comment]
This seems [neat](https://k1ss.org/blog/20200625a#4.0). Maybe something like `xdoc` can be added to xtools.

**Comment by ericonr** [comment]
It does! I would just add it as a command in the `void-docs` package, actually. I guess we would need something like tags/subject lines in each file for this to work? Or perhaps use the page title for it?

**Comment by flexibeast** [comment]
@ericonr: What's the current status of https://github.com/void-linux/void-packages/pull/21453? Are there any blockers we need to work on in this repo?

**Comment by ericonr** [comment]
I definitely need to update the build template, at least. Will have a look at current issues and PRs, too.

**Comment by flexibeast** [comment]
@ericonr: We can now close this, yes? :-D

**Comment by ericonr** [comment]
Indeed! :D
