### ISSUE TITLE
asc file refered to in downloads doesn't exist

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-docs#232]
https://docs.voidlinux.org/installation/live-images/downloading.html#verify-image-authenticity links to the Void GPG key, which errors out with 404 right now (https://alpha.de.repo.voidlinux.org/live/current/void_images.asc). We should probably reword this part.

@the-maldridge I'm not sure how to explain this one. Should I just remove the mention about it being possible to download the asc file from that link?

**Comment by the-maldridge** [comment]
Probably best to just remove it.  New images are signed with signify, and the key is long expired for that GPG key pair.

**Comment by ericonr** [comment]
From https://voidlinux.org/download/ :

> The sha256.txt file contains the SHA256 hashes to verify the integrity of the downloaded files; this file is digitally signed with a gpg key.

We should reword this one, too. And I'm wondering if moving all the verification to the docs would be better.

**Comment by ericonr** [comment]
Fixed by #233 when it lands
