### ISSUE TITLE
Expand Xorg section to include basic setup of xinit/a display manager

### ISSUE THREAD

**Issue by wallisers** [void-linux/void-docs#239]
It would be nice, if the Xorg sections would be expanded to contain the basic setup of a Xsession and how it is hooked up to either `xinit`/`startx` or a display manager. I really had issues with this when I was setting up my first minimalist Linux installation.

I know, that this is highly distro agnostic, but I think of it as an entry point for new users. (A starting point for more detailed research, so to say)

**Comment by ericonr** [comment]
@wallisers have you taken a look at #254? Do you think we need any more information about it?

**Comment by flexibeast** [comment]
Closing this via https://github.com/void-linux/void-docs/commit/c68e470f3c910e6660a2bb4c0a46c0434aa0ac40.

**Comment by wallisers** [comment]
> @wallisers have you taken a look at #254? Do you think we need any more information about it?

This is sufficient.
Sorry for the delayed answer...
