### ISSUE TITLE
Manage custom kernels with xbps-src?

### ISSUE THREAD

**Issue by travankor** [void-linux/void-docs#252]
I don't know if this should be added, but I remember a lot of users asking about either the `-libre` or `-zen` custom kernels. Describing how people can maintain their own kernel might be a good idea (or not?).

This might not be wanted since this is just an extended example of using `xbps-src`, but this doesn't really belong in the void-packages repo either.

**Comment by Vaelatern** [comment]
We typically do not encourage custom packages, I don't think we want to encourage it either. People who want libre kernels can read void-packages and figure out what to change.

**Comment by ericonr** [comment]
I also think we shouldn't document it, but I just saw a new post about it on reddit. And well, some people need kernels not for customization, but for stuff like Chromebooks or Surface laptops. So perhaps there are good reasons for them.

**Comment by Vaelatern** [comment]
There are good reasons, let the documentation be on reddit and not our responsibility?

**Comment by travankor** [comment]
Hardware device support might be a more valid use-case that I forgot to mention -- There were plans some time ago to drop device-specific kernels, like `usbarmory` and `kirkwood`.

Unfortunately, 90% of ARM boards require custom vendor kernels (even if they're open-source, the vendors are apparently too lazy to upstream their changes).

Closing this, but I think this can be incorporated into #133 and maybe #262.
