### ISSUE TITLE
iptables and nftables

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-docs#266]
Nftables is currently completely missing.

The current iptables documentation seems low quality imho.

* The section [IP6 firewall rules](https://docs.voidlinux.org/config/network/iptables.html#ip6-firewall-rules) could be merged with "Applying the rules at boot", the `iptables-runit` service works already for both, the snipped for `/etc/rc.local` could do exactly the same.
* [Firewall rules](https://docs.voidlinux.org/config/network/iptables.html#firewall-rules) and its subsection [Adjusting the rules](https://docs.voidlinux.org/config/network/iptables.html#adjusting-the-rules) explain how to edit files, which shouldn't be necessary. They also miss to document the file names of the rules which would be loaded on boot with the `rc.local` snipped, the runit "service" and the `iptables-runit` core service.

**Comment by ericonr** [comment]
The only firewall I've ever used was ufw, so I don't think I'm qualified to write about them. I can do some research, however, if no one manages to write this one.

The stylistic part I can do, but if anyone wants to claim it, I'd be happy to help them!
