### ISSUE TITLE
Post Installation

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-docs#268]
The [Post Installation](https://docs.voidlinux.org/config/post-install.html) section contains nothing worthwhile, I think it would make sense to remove this page and add a note to the installation guides to update the system after installing if necessary.
Also not really configuration related, if someone wants to keep a page like this I think even if its "Post Installation", it would still make sense to keep it in the "Installation" section.

**Comment by flexibeast** [comment]
Closed by https://github.com/void-linux/void-docs/commit/a1469911e6399bfd28b70513a6d5b88e640e50de.
