### ISSUE TITLE
Java Documentaion

### ISSUE THREAD

**Issue by MylesLandais** [void-linux/void-docs#287]
No results found for Java in the docs.

Would like to see the manual install or instructions for a java8 setup copied over.

https://wiki.voidlinux.org/Java#JDK8

**Comment by flexibeast** [comment]
@void-linux/pkg-committers: Thoughts on this?

**Comment by jnbr** [comment]
The stuff on the wiki is outdated. I don't think we need to document `xbps-install openjdk`.

**Comment by ericonr** [comment]
@jnbr I think they mean installation instructions for pulling specific versions from oracle's website. I'm not super into that idea, but I don't use Java so idk what's needed for it.

**Comment by jnbr** [comment]
I wouldn't document this part either, it is not specific to void.

**Comment by Vaelatern** [comment]
Agreed. `xbps-install oraclejdk` or `xbps-install openjdk` and be done.
