### ISSUE TITLE
Title casing for headers

### ISSUE THREAD

**Issue by pltrz** [void-linux/void-docs#29]
I noticed that there are some incensistencies in the title casings for headers. Some are capitalized on only the first word, some on all of them, and some others etc.

We should decide on a style and add it to the style guide; we should then comb through the existing documentation and bring it all up to speed.

**Comment by bobertlo** [comment]
I had been naturally capitalizing all words, but noticed they were mostly not and stopped. I would vote all capitalized, but don't really care.

**Comment by pltrz** [comment]
[Here](https://en.wikipedia.org/wiki/Letter_case#Case_styles) are a few case styles described on wikipedia.

Here are the conventions used by the Arch Wiki to add to the discussion:

- <https://wiki.archlinux.org/index.php/Help:Style#Title>
- <https://wiki.archlinux.org/index.php/Help:Style#Section_headings>

They use sentence case over there.

**Comment by CameronNemo** [comment]
I would prefer capitalizing all words in the title of a page, but only capitalizing the first word in subheadings.

**Comment by pltrz** [comment]
My personal vote would be for sentence case in both titles and subheadings, ie. capitalizing only the first word.

**Comment by bobertlo** [comment]
There seems to be momentum behind sentence casing. I don't have a strong opinion on capitalization, but think it should be consistent between titles and subheadings.

**Comment by pltrz** [comment]
I've been doing a bit more digging into what conventions are for other groups.

Organizations that use sentence casing:
- [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Naming_conventions_(capitalization))
- [Gentoo Wiki](https://wiki.gentoo.org/wiki/Gentoo_Wiki:Guidelines#Titles_and_section_headings)
- [University of Oxford Public Affairs](https://www.ox.ac.uk/public-affairs/style-guide?wssl=1)
- [Debian Wiki](https://wiki.debian.org/DebianWiki/EditorGuide#pages-name) - page titles there use CamelCase, but for headers seems like most pages use sentence case, but some don't. They are also not super clear in the EditorGuide and don't mention it explicitly, for headers as far as I can tell.

Title casing:
- [Ubuntu](https://help.ubuntu.com/community/Installation) - I didn't find it mentioned in their style guide, which was a bit hard to navigate but from looking at the pages, seems like they definitely go title case.

Inconsistent:
- Alpine Linux Wiki doesn't specify anything in their [guidelines](https://wiki.alpinelinux.org/wiki/Help:Editing) and when looking through the wiki I found it to be incensistent. It tends towards title case but many pages are sentence case.

--------------------------------

Some answers people gave in [unix stackexchange](https://ux.stackexchange.com/questions/28297/should-we-use-title-case-or-sentence-case-for-headlines-and-buttons). Granted, the question isn't aimed at our use-case but the answers give some insight.

-----------------------------------

My original preference was not based on any substance and just kind of random. After these findings though, my vote will continue being for sentence casing for titles and headers. That being said, to me consistency is the most important thing so we should just decide and take action.

**Comment by the-maldridge** [comment]
Lets use title case for page titles and sentence case for everything else.

**Comment by bobertlo** [comment]
^ works for me. I still don't really care, but guess I would prefer title case for page titles, especially after looking at TOC
