### ISSUE TITLE
Xorg section should describe modesetting vs DDX

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#303]
As suggested by @st3r4g in [this comment](https://github.com/void-linux/void-docs/pull/297#discussion_r430277148):

> I think we need a paragraph in the xorg section explaining that Xorg can run with two different kinds of graphics drivers: 'modesetting' vs 'DDX', and how to check what you're running.

**Comment by st3r4g** [comment]
I'll open a PR for this
