### ISSUE TITLE
Document how to disable bitmap fonts

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#316]
As per @abenson's comment [here](https://github.com/void-linux/void-packages/issues/22477#issuecomment-636532354):

> I think this should be documented in the handbook. I don't think disabling bitmap fonts for everyone is the right answer.

**Comment by ericonr** [comment]
I hate that man pages don't seem to document that sort of procedure at all. I think we'd have to list the steps.

**Comment by flexibeast** [comment]
Closed by #351.
