### ISSUE TITLE
One more tier for mirros?

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-docs#326]
I have been warned that https://mirror.aarnet.edu.au/pub/voidlinux/ is a bit out of date, which can be seen by their `current/` folder, which hasn't been updated since 2018. They do provide hosting for docs, images, xbps-static and xlocate database, which are still very useful. Should we make a note about this, create another tier of mirrors or perhaps another column in the table with observations? Or just leave as is?

**Comment by Vaelatern** [comment]
We make no guarantees about 2nd tier mirrors. To further split hairs would just waste time.

**Comment by ericonr** [comment]
Fair enough. Thanks c:
