### ISSUE TITLE
Move information from Void Web site to Handbook

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#329]
As described in https://github.com/void-linux/void-linux.github.io/pull/90, we need to make sure the content in the [usage/runit](https://voidlinux.org/usage/runit/), [usage/XBPS](https://voidlinux.org/usage/xbps/) and [FAQ](https://voidlinux.org/faq/) pages on the Void Web site is instead covered by the Handbook.

- [x] usage/runit
   https://github.com/void-linux/void-linux.github.io/pull/104
- [x] usage/XBPS
   #358, https://github.com/void-linux/void-linux.github.io/pull/107
- [x] FAQ
   #346, https://github.com/void-linux/void-linux.github.io/pull/105

**Comment by ericonr** [comment]
Regarding runit:

It mentions all the runit related utilities, but they are already mentioned in runit's man pages, and their function is explained in the relevant sections of the handbook, if needed.

It has an example for how to switch the runsvdir, using

```
runsvchdir my_runlevel
```

which I have no idea if it's recommended or not.

**Comment by flexibeast** [comment]
Blocked on #346.

**Comment by flexibeast** [comment]
@ericonr: i think the reference to the `runsvchdir(8)` man page in the "Services and Daemons - runit" section is probably sufficient. More generally, it seems to me the Handbook adequately covers the contents of `usage/runit`; if you agree, i'll open a PR in void-linux/void-linux.github.io to modify the landing page to point to the above Handbook section, and to remove `usage/runit`.

**Comment by flexibeast** [comment]
Blocked on #358.

**Comment by flexibeast** [comment]
With #358 now closed, this issue can be closed.
