### ISSUE TITLE
Upon merge of void-packages #22249, modify "NVIDIAOptimus" section

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#334]
As per @st3r4g's request [here](https://github.com/void-linux/void-packages/pull/22249#issuecomment-633256606):

> after this gets merged, can you modify https://docs.voidlinux.org/config/graphical-session/graphics-drivers/optimus.html#prime-render-offload mentioning that the script is already provided?

**Comment by st3r4g** [comment]
It was merged. Another little thing, can you also fix NVIDIAOptimus -> NVIDIA Optimus in SUMMARY.md?

**Comment by flexibeast** [comment]
So something like:

> on the NVIDIA GPU, as done by the provided `prime-run` wrapper script:

?

> can you also fix

Sure, will do.

**Comment by ericonr** [comment]
About that... https://github.com/rust-lang/mdBook/issues/1218

**Comment by ericonr** [comment]
@flexibeast I can do this one, unless you've already started on it.

**Comment by flexibeast** [comment]
@ericonr: No, i hadn't already started; go ahead.

Re. that mdBook issue, ah okay. Related: i had to change the title of the "Installation via chroot" section (to "x86/x86_64" rather than "x86 or x86_64") to make it short enough to - just - fit within the 80-character limit.

**Comment by ericonr** [comment]
@flexibeast @st3r4g https://github.com/rust-lang/mdBook/pull/1291 :D
