### ISSUE TITLE
Ensure relevant content from wiki FAQ page is covered by Handbook

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#337]
[Wiki "Frequently Asked Questions" page](https://wiki.voidlinux.org/Frequently_Asked_Questions):

- [x] 1.1 Is Void an Arch Linux fork?
   Void [landing page](https://voidlinux.org) has a "Not a fork" section.
- [x] 1.2 Is there a 'Stable' version of Void?
   #349 (merged)
- [x] 1.3 Void Linux name origin
   #349 (merged)
- [x] 2.1 How should I partition my disk?
   Covered by "Partitioning Notes" section in Handbook.
- [x] 2.2 The installer sucks, how can I do $SPECIALTHING on installation?
   Covered, and being covered, by advanced guides.
- [x] 2.3 How can I change my users default shell?
   Out-of-scope, unneeded.
- [x] 2.4 How do I remove old kernels?
   Covered by "Kernel" section in Handbook.
- [x] 2.5 How can I load kernel modules at boot?
   Covered by "Kernel" section in Handbook.
- [x] 2.6 How do I blacklist kernel modules?
   Covered by "Kernel" section in Handbook.
- [x] 2.7 How to get rid of "ataN: softreset failed (device not ready)" ?
   Out-of-scope, unneeded.
- [x] 2.8 How do I set up/start/stop services?
   Covered by "Services and Daemons - runit" section in Handbook.
- [x] 3.1 Which package contains XYZ?
   Covered by "Finding Files" section in Handbook.
- [x] 3.2 How do I get a list of installed packages?
   #343 (merged)
- [x] 3.3 I want to downgrade a package!
   Covered by "Downgrading to a specific package version" section in Handbook.
- [x] 3.4 I installed $PKGNAME and it's not in my $PATH!
   #404 (merged)
- [x] 3.5 A 'Transaction aborted due to unresolved shlibs' error is preventing me from updating!
   Covered by "Common Errors" section in Handbook.
- [x] 4.1 Valgrind needs glibc-dbg, which cannot be found. Help?
   Covered by "debug" section of Handbook.
- [x] 4.2 How do I check template files for common errors?
   Covered by void-packages/CONTRIBUTING.md.
- [x] 5.1 [Why] doesn't $MANWIDTH change the man pages' width?
   Covered by `man man` and `man man.conf`.
- [x] 5.2 [Why] is tar/Engrampa/XYZ unable to unpack *tar.xz archives?
   Out-of-scope, unneeded
- [x] 5.3 [Why] isn't my gamepad detected by some apps (e.g. supertux2)?
   Out-of-scope, unneeded
- [x] 5.4 [Why] isn't a newly packaged kernel immediately offered by XBPS for installation?
   #344 (merged)
- [x] 6.1 [How] do I install a newer kernel manually?
   #344 (merged)
- [x] 6.2 [How] do I add an user account?
   Covered by "Users and Groups" section in Handbook.
- [x] 6.3 [How] do I set up my locale?
   Covered by "Locales" section in Handbook.
- [x] 6.4 [How] do I set the timezone?
   Covered by "Date and Time" section in Handbook.
- [x] 6.5 [How] do I suspend/hibernate/shutdown/reboot the system using the console?
   #342 (merged)
- [x] 6.6 [How] do I make my NTFS partitions writable?
   Out-of-scope, unneeded
- [x] 7.1 Is there a Void Linux mailing list?
  Refer to [this comment](https://github.com/void-linux/void-docs/issues/337#issuecomment-662185268)

**Comment by flexibeast** [comment]
At this point i'd like some feedback from more senior members of the Void team. The remaining items are:

- [ ] 2.2 The installer sucks, how can I do $SPECIALTHING on installation?
- [ ] 3.4 I installed $PKGNAME and it's not in my $PATH!
- [ ] 5.2 [Why] is tar/Engrampa/XYZ unable to unpack *tar.xz archives?
   Out-of-scope? Unneeded?
- [ ] 5.3 [Why] isn't my gamepad detected by some apps (e.g. supertux2)?
   Out-of-scope? Unneeded?
- [ ] 6.6 [How] do I make my NTFS partitions writable?
   Out-of-scope? Unneeded?
- [ ] 7.1 Is there a Void Linux mailing list?

* Can people confirm whether my assessments of 5.2, 5.3 and 6.6 are correct?
* Should 2.2 and 3.4 go in the Handbook somewhere?
* i'm not sure how to deal with 7.1, given that we technically do have a mailing list, but it's effectively dead?

**Comment by ericonr** [comment]
All of the out of scope questions look like they are about linux in general and don't apply to Void specifically. I agree with your judgement there.

For 2.2, we already link the advanced guides in `installation/index`. Unless you're asking if we should include all those guides, which might be an important question.

I think 3.4 might fit somewhere, but I'm not entirely sure. Either in a XBPS or troubleshooting page. For java this issue is solved with alternatives, though.

For 7.1, it depends on the patch for showing the ML on the front page gets accepted, I guess.

**Comment by flexibeast** [comment]
@ericonr: Thanks!

i've now checked off the "out-of-scope" items.

Re. advanced guides, i think in terms of this specific GH issue, 2.2 can be checked off, since we're tracking the creation of such guides via #327. Ok?

Re. 3.4, i don't recall people generally seeming to have this problem; more often it's that the binary isn't named what they expect. Is that your experience also? If so, we could mention use of `xbps-query -f` somewhere in the "XBPS" section. WDYT?

Re. 7.1, yeah, https://github.com/void-linux/void-linux.github.io/issues/83 is a blocker.

**Comment by ericonr** [comment]
> Re. advanced guides, i think in terms of this specific GH issue, 2.2 can be checked off, since we're tracking the creation of such guides via #327. Ok?

Yes, good idea c:

> Re. 3.4, i don't recall people generally seeming to have this problem; more often it's that the binary isn't named what they expect. Is that your experience also? If so, we could mention use of xbps-query -f somewhere in the "XBPS" section. WDYT?

Most of the time it is! I guess we could try to list `xbps-query -f` for more than only executables, so something like "if you can't find the files provided by a package, you can check what files are contained in that package using: ..."

**Comment by flexibeast** [comment]
> Yes, good idea c:

Thanks, done.

> I guess we could try to list xbps-query -f for more than only executables, so something like "if you can't find the files provided by a package, you can check what files are contained in that package using: ..."

Good idea. Add to "Finding files and packages" subsection of `xbps/index`?

**Comment by ericonr** [comment]
I'm not entirely sure on where to add it. But for now that's probably where it fits better, so yeah.

**Comment by flexibeast** [comment]
Re. 7.1, [this list post](https://groups.google.com/forum/#!msg/voidlinux/05eYK1l0i2I/V2rgUaAmBAAJ) says:

> I spoke on IRC with maldridge, who has commit access to the website repo. He would prefer not to link to the mailing list at this time, citing low readership and limited developer capacity.

So i'll check off 7.1 and close this issue.
