### ISSUE TITLE
Ensure relevant content from Web site FAQ is covered by Handbook

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#346]
Needed to partially address #329.

[Void site FAQ](https://voidlinux.org/faq/):

- [x] Introduction
   Empty section.
- [ ] Installation
   #355
- [x] Downloading
   Section header.
- [x] Live Images
   Empty section.
- [x] Static XBPS binaries
   Covered by "Static XBPS" section.
- [x] Verifying integrity
   Covered by "Downloading Installation Media" section.
- [x] Using the Installer
   Covered by "Installation Guide" section.
- [x] Manual installation
   Empty section.
- [x] Post installation
   Empty section.
- [x] System Management
   Section header.
- [x] System services and daemons
   Covered by "Services and Daemons - runit" section.
- [x] Per user service directory
   Covered by "Per-User Services" section.
- [x] Cron
   Covered by "Cron" section.
- [x] Logging
   Section header.
- [x] Syslog
   Covered by "Logging" section.
- [x] Console (tty, getty, agetty)
   Section header.
- [x] Disabling default ttys
   Covered by "Service and Daemons - runit" section.
- [x] Changing the default shell
   Out-of-scope, unneeded.
- [x] Kernel
   Section header.
- [x] Kernel series
   Covered by "Kernel" section.
- [x] Removing old kernels
   Covered by "Kernel" section.
- [x] Kernel modules
   Covered by "Kernel" section.
- [x] Loading kernel modules at boot
   Covered by "Kernel" section.
- [x] Blacklisting kernel modules
   Covered by "Kernel" section.
- [x] dracut
   Covered by "Kernel" section.
- [x] mkinitcpio
   Covered by "Kernel" section.
- [x] Kernel hooks
   Covered by "Kernel" section.
- [x] Dynamic Kernel Module Support (dkms)
   Covered by "Kernel" section.
- [x] cmdline
   Covered by "Kernel" section.
- [x] grub
   Covered by "Kernel" section.
- [x] dracut
   Covered by "Kernel" section.
- [x] Manual pages
   #348 (merged)
- [x] Packages
   Covered in multiple places, e.g. "About" section.
- [x] Package Management
   Section header.
- [x] Searching a file
   Covered by "Finding Files" section.
- [x] Building Packages
   Covered by void-packages/README.md.
- [x] Contributing
   Link to void-packages/CONTRIBUTING.md provided at voidlinux.org/contribute.
- [x] Debugging packages
   Covered by "debug" section.
- [x] Available Mirrors
   Covered by "Mirrors" section.
- [x] Changing mirrors
   Covered by "Changing Mirrors" section.
- [x] Disk Setup
   Empty section.
- [x] Networking
   Covered by "Network" section.
- [x] Interface names
   Covered by "Network" section.
- [x] Static Setup
   Covered by "Network" section.
- [x] DHCP
   Section header.
- [x] dhcpcd
   Covered by "Network" section.
- [x] dhclient
   Empty section.
- [x] NetworkManager
   Empty section.
- [x] wicd
   Empty section.
- [x] wpa_supplicant
   Empty section.
- [x] Xorg
   Empty section.
- [x] Drivers
   Empty section.
- [x] Display managers
   Empty section.
- [x] Session and seat management
   Covered by "Session and Seat Management" section.
- [x] ConsoleKit2
   CK2 deprecated, unmaintained, removed from repos - unneeded.
- [x] elogind
   Covered by "Session and Seat Management" section.
- [x] Multimedia
   Section header.
- [x] Audio setup
   Covered by "Multimedia" section.
- [x] Alsa
   Covered by "ALSA" section.
- [x] PulseAudio
   Covered by "PulseAudio" section.

**Comment by ericonr** [comment]
I think default ttys are explained in the service pages now, aren't they?

**Comment by flexibeast** [comment]
@ericonr: Ah, yes, you're right - sorry for missing that. Task list updated.

**Comment by flexibeast** [comment]
So the only thing left to address is whether we want to mention

> The following features are not supported by the installation script:
>
>    LVM
>    Luks
>    ZFS

in the Handbook (presumably in the "Installation Guide" section)? My vote is "yes", and that we add links to the specific guides for those things as they're included.
