### ISSUE TITLE
Ensure relevant content from `usage/xbps/` on Web site is covered by Handbook

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#358]
Needed to partially address #329.

[usage/xbps/](https://voidlinux.org/usage/xbps/):

- [x] Introduction
  Covered by "XBPS Package Manager" section of Handbook.
- [x] Repositories
  Covered by "Custom Repositories" section of Handbook.
- [x] Official Repositories
  Covered by "Official Repositories" subsection of Handbook.
- [x] Official Repositories (musl)
   #394 (merged)
- [x] Subrepositories
  Covered by "Repositories" section of Handbook.
- [x] Download static binaries
  Covered by "Static XBPS" section of Handbook.
- [x] xbps-install(1)
  Covered by man page and "XBPS Package Manager" section of Handbook. 
- [x] Synchronize remote repository data
  Covered by man page.
- [x] Installing/updating a single package
  Covered by man page.
- [x] Reinstalling/downgrading to a specific package version
  Covered by man page and "Downgrading" subsection of Handbook.
- [x] Updating your system
  Covered by man page and "Updating" subsection of Handbook.
- [x] xbps-query(1)
  Covered by man page and "XBPS Package Manager" section of Handbook.
- [x] Listing registered repositories
  Covered by man page.
- [x] Listing installed packages
  Covered by man page.
- [x] Showing information for a package
  Covered by man page and "XBPS Package Manager" section of Handbook.
- [x] Showing the files list for a package
  Covered by man page.
- [x] Showing the required dependencies for a package
  Covered by man page.
- [x] Showing the reverse dependencies for a package (packages that depend on it):
  Covered by man page.
- [x] Searching for packages matching its package name/version and/or description
  Covered by man page.
- [x] Searching for packages matching a filename
  Covered by man page.
- [x] xbps-remove(1)
  Covered by man page and "XBPS Package Manager" section of Handbook.
- [x] Removing a single package
  Covered by man page.
- [x] Removing a single package and recursively all packages that were installed as dependencies
  Covered by man page.
- [x] Cleaning up the cache directory
  Covered by man page.
- [x] Removing all package orphans
  Covered by man page.
- [x] Removing all package orphans and clean the cache directory
  Covered by man page.
- [x] xbps-reconfigure(1)
  Covered by man page and "XBPS Package Manager" section of Handbook.
- [x] Configure a package that is in unpacked state
  Covered by man page.
- [x] Configure all packages that are in unpacked state
  Covered by man page.
- [x] Force reconfiguration of a package (even if it was configured previously):
  Covered by man page.
- [x] xbps-pkgdb(1)
  Covered by man page and "XBPS Package Manager" section of Handbook.
- [x] Checking for errors in an installed package
  Covered by man page.
- [x] Checking for errors in all installed packages
  Covered by man page.
- [x] Changing properties of an installed package
   #393 (merged)
- [x] xbps-rindex(1)
   #393 (merged)
- [x] Creating a local repository
  Covered by man page and "Custom Repositories" section of Handbook.
- [x] Adding a specific package to a repository
  Covered by man page.
- [x] Force addition of a specific package to a repository
  Covered by man page.
- [x] Cleaning a repository (removing stalled entries)
  Covered by man page.
- [x] Removing obsolete packages in a repository
  Covered by man page.
- [x] Signing a repository
  Covered by man page and "Signing Repositories" section of Handbook.
- [x] xbps-alternatives(1)
  Covered by man page and "XBPS Package Manager" section of Handbook.
- [x] List all alternatives
  Covered by man page.
- [x] List alternatives for a specific package
  Covered by man page.
- [x] Set all alternative groups
  Covered by man page.
- [x] Set specific alternative groups
  Covered by man page.

**Comment by ericonr** [comment]
We should add redirects for the usage pages, I think. `voidlinux.org/usage/{runit,xbps}` should lead to the related `docs.voidlinux.org` page.

That way, the links anyone might have bookmarked will keep working, as will the links currently in the #voidlinux channel message (but these last ones should be changed).

**Comment by flexibeast** [comment]
Certainly. The link to `usage/runit` has already been removed from the landing page, but a redirect could be added at the Web server level - we'd have to ask @the-maldridge about doing that. We can add a redirect for `usage/xbps` once this issue has been closed.

**Comment by ericonr** [comment]
Do you think adding the usage/runit page back to make it a redirect would be too bad?

**Comment by flexibeast** [comment]
Yeah, i don't think that's necessary, unless we're sure there are a number of people reporting being affected. An initial search for references to 'voidlinux.org/usage/runit' suggests this probably isn't a significant concern.

**Comment by flexibeast** [comment]
The three remaining items are now:

- [ ] Official Repositories (musl)
  Do we want/need to specifically mention the musl URL somewhere, e.g. in the "Downloading installation media" subsection?
- [ ] Changing properties of an installed package
   This information can certainly be found in `xbps-pkgdb(1)` man page, but i think it might be nice to have something like this content in the "Advanced Usage" section.
- [ ] xbps-rindex(1)
Is there any strong reason to *not* mention `xbps-rindex(1)` amongst the XBPS tools listed in the "XBPS Package Manager" section? The only other places it's mentioned are in the "Downgrading" subsection and in the "Signing repositories" section; i think it would be good to mention that it's a tool to "manage local binary package repositories" (to quote the man page), and i don't see any particular harm in doing so.

**Comment by ericonr** [comment]
I don't remember where exactly we mention that you should add `current` to the mirror URL, but it would be nice to mention `musl` and `aarch64` there as well. Both are different from current.

Which capabilities of xbps-pkgdb would you like to explicitly mention?

I don't see any harm in having rindex there either.

**Comment by flexibeast** [comment]
> I don't remember where exactly we mention that you should add current to the mirror URL, but it would be nice to mention musl and aarch64 there as well. Both are different from current.

\*nod\* Will do.

> Which capabilities of xbps-pkgdb would you like to explicitly mention?

Definitely 'hold', and possibly 'repolock', as i regularly see people asking questions for which these things are the answer. :-)

> I don't see any harm in having rindex there either.

Thanks, i'll add it in.

**Comment by flexibeast** [comment]
With #394 now merged, this issue can be closed.
