### ISSUE TITLE
documentation Request: documentation on setting up a void packages mirror

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-docs#392]
Is there any chance of documentation on how to set up a mirror for helping out with getting people packages via xbps? I was thinking of setting up a virtual server to use with xbps for people in my area.

**Comment by flexibeast** [comment]
My first thought is "no", given that how to mirror something isn't Void-specific information, and there are already existing guides to the process available elsewhere (e.g. [here](https://www.eff.org/keeping-your-site-alive/mirroring-your-site)). @ericonr, thoughts?

**Comment by ericonr** [comment]
I mostly agree. I think we could link to one such guide (EFF <3), as an example. Not sure if it's easy to fit into the current structure.

**Comment by flexibeast** [comment]
Could we perhaps add a subsection to `mirrors/index` saying something like (very roughly):

> If you'd like to set up a mirror, follow one of the many guides available (e.g. \<EFF guide\>), then submit a PR to the `void-docs` repo which adds your mirror to this page.

?

**Comment by ericonr** [comment]
I like that option.

**Comment by Frick-David** [comment]
Nice!
