### ISSUE TITLE
Elaborate on GPT partition table + BIOS boot

### ISSUE THREAD

**Issue by harrisonthorne** [void-linux/void-docs#425]
[Section in question](https://docs.voidlinux.org/installation/live-images/partitions.html#bios-system-notes)

> It is possible to install a GPT partition table on a BIOS system, but grub will need a special partition to boot properly.

I'm hoping for a little more elaboration on this or a link to an article describing what *specifically* GRUB needs to work (which is, if I understand correctly, a 1MB partition with type `BIOS boot`).

I think this improvement might save some trouble with some users (like me). :)

**Comment by harrisonthorne** [comment]
[This section](https://docs.voidlinux.org/installation/live-images/guide.html#partition) more or less has the same issue:

> Advanced users may use GPT but will need to create a special BIOS partition for grub to boot.

**Comment by ericonr** [comment]
Would you like to make a PR for this? I actively run from GRUB, so I don't know much about it, but I can certainly try to review the info.

**Comment by harrisonthorne** [comment]
@ericonr Sure thing! I'll get into it when I get the chance. I'll make a reminder for myself.

**Comment by ericonr** [comment]
Closed in db9ed78
