### ISSUE TITLE
Move style guide out of handbook

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-docs#444]
There was a PR for this I think but it had unrelated changes that were disagreed on and it has drifted heavily. I think it would be more appropriate to have this guide in the root of the repository as a markdown file and link to that from the contributing section.

This could maybe just be called contributing.md and include git best practice also? Or that could go in the README?

I'm open to discussion but I don't feel like this is part of using void Linux exactly and could be moved out. Especially in light of the pdf and upcoming tagged releases.

**Comment by bobertlo** [comment]
Related to #407

**Comment by flexibeast** [comment]
Yeah, i like the idea of moving "Style Guide" and "Submitting Changes" to [CONTRIBUTING.md](https://github.com/void-linux/void-docs/blob/master/CONTRIBUTING.md) - the current CONTRIBUTING.md simply refers people to those sections, so moving those sections there would also remove a layer of indirection. :-)

**Comment by flexibeast** [comment]
@ericonr: Any objections? If not, i'll create a PR for this.

**Comment by ericonr** [comment]
I think it makes sense. Go for it!

**Comment by flexibeast** [comment]
Closed by #446.
