### ISSUE TITLE
fail2ban missing Documentation 

### ISSUE THREAD

**Issue by littlewing7** [void-linux/void-docs#454]
I see the wiki page is deprecate, can you please update the documentation adding updated instructions for fail2ban?

Many thanks for your work 

Massimo

**Comment by flexibeast** [comment]
Looking at [the old wiki page](https://wiki.voidlinux.org/Fail2ban_-), the main reason to have it was some issues with the `fail2ban` package. However, the `fail2ban` [runit service](https://github.com/void-linux/void-packages/blob/master/srcpkgs/fail2ban/files/fail2ban/run) now creates the `/var/run/fail2ban` directory; and although it doesn't provide a `fail2ban-client` service, all [that service](https://wiki.voidlinux.org/Fail2ban_-#Create_Missing_Bits) did was create `/var/run/fail2ban` if it didn't exist, tried to ensure the `fail2ban` service was running, then do `fail2ban-client reload`. So as far as i can tell, there's nothing we should be documenting that shouldn't be covered by [the fail2ban documentation](https://www.fail2ban.org/wiki/index.php/Main_Page) itself.

**Comment by littlewing7** [comment]
Hi

the wiki is not correct, mainly in regards with
/var/log/socklog/secure/current, because the filter is not matching
anything.

I think because the socklog sshd log generated is changed, so the suggested
filter is not matching anything.

for examples I have a log with more than 6000 lines, but nothing is matched
(using the suggested filter form the wiki):

------------------------
[INCLUDES]
before = common.conf

[Definition]
_daemon = sshd

failregex = sshd.*Did not receive identification string from <HOST>\s*$
            sshd.*Received disconnect from <HOST>.*preauth.*\s*$
            sshd.*Disconnected from <HOST>.*preauth.*\s*$
            sshd.*Invalid user (\w+) from <HOST>\s*$

ignoreregex =

[Init]
# "maxlines" is number of log lines to buffer for multi-line regex searches
maxlines = 10
-------------------

[root@void-router ~]# fail2ban-regex -v
/var/log/socklog/secure/@400000005f2d40a739a5493c.s
/etc/fail2ban/filter.d/sshd.local

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 10
Use      datepattern : Default Detectors
Use         log file : /var/log/socklog/secure/@400000005f2d40a739a5493c.s
Use         encoding : UTF-8


Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] sshd.*Did not receive identification string from <HOST>\s*$
|   2) [0] sshd.*Received disconnect from <HOST>.*preauth.*\s*$
|   3) [0] sshd.*Disconnected from <HOST>.*preauth.*\s*$
|   4) [0] sshd.*Invalid user (\w+) from <HOST>\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [6884] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|
 ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?:
ExYear)?
|  [0] {^LN-BEG}(?:DAY )?MON Day ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] {^LN-BEG}Day(?P<_sep>[-/])Month(?P=_sep)(?:ExYear|ExYear2)
%k:Minute:Second
|  [0] {^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[
:]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] {^LN-BEG}Month/Day/ExYear:24hour:Minute:Second
|  [0] {^LN-BEG}Month-Day-ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] {^LN-BEG}Epoch
|  [0] {^LN-BEG}ExYear2ExMonthExDay  ?24hour:Minute:Second
|  [0] {^LN-BEG}MON Day, ExYear 12hour:Minute:Second AMPM
|  [0] {^LN-BEG}ExYearExMonthExDay(?:T|
 ?)Ex24hourExMinuteExSecond(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] {^LN-BEG}(?:Zone name )?(?:DAY )?MON Day
%k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}(?:Zone offset )?(?:DAY )?MON Day
%k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}TAI64N
|  [0] {^LN-BEG}24hour:Minute:Second
|  [0] ^<Month/Day/ExYear2@24hour:Minute:Second>
|  [0] ^MON-Day-ExYear2 %k:Minute:Second
`-

Lines: 6884 lines, 0 ignored, 0 matched, 6884 missed
[processed in 0.82 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all
6884 lines

So the are a problem on documentation for fail2ban

Many thanks

Massimo




Il giorno ven 7 ago 2020 alle ore 13:35 Alexis <notifications@github.com>
ha scritto:

**Comment by flexibeast** [comment]
Sorry, it appears i've miscommunicated.

i'm not saying that the information on the wiki is correct. i'm saying that:

* the only Void-specific information on the wiki page appears to no longer be an issue;

* the sort of information found on the old wiki page should be searched for in the `fail2ban` documentation.

[The Handbook says](https://docs.voidlinux.org/about/about-this-handbook.html):

> This handbook is not an extensive guide on how to use and configure common Linux software ... Those looking for tips and tricks on how to configure a Linux system in general should consult upstream software documentation.

We don't try to provide documentation for all the possible ways of configuring, and using, all the possible software that can be run on Void (not least because we're all volunteers already trying to do as much as we can). We generally expect upstreams - i.e. the creators of the software we package - to provide adequate documentation. If you find their documentation isn't helpful for you, please ask them to improve their documentation (just as, if you couldn't work out how to use Photoshop on Windows, you'd ask Adobe to improve their documentation, not Microsoft).

**Comment by flexibeast** [comment]
Closing as out of scope.
