### ISSUE TITLE
Void Handbook Cover

### ISSUE THREAD

**Issue by argosatcore** [void-linux/void-docs#479]
Hello Void team,

More than a feature request, this is a token of my appreciation towards your hard work. I made a little cover for the Void Handbook. If the cover is of your liking, feel free to incorporate it to the handbook. I'm also open to suggestions. I will also understand if the cover doesn't fit the handbook style. I will attach three variations of the same cover: light, dark and darker.

![VHC Darker Gray](https://user-images.githubusercontent.com/64110504/90711579-593a0800-e25e-11ea-8390-648fcc9df5fd.png)
![VHC Dark Gray](https://user-images.githubusercontent.com/64110504/90711580-5a6b3500-e25e-11ea-86c2-59d5d35dcd15.png)
![VHC Dark Light](https://user-images.githubusercontent.com/64110504/90711581-5a6b3500-e25e-11ea-9b77-00ac7c323202.png)

**Comment by the-maldridge** [comment]
This looks really well done, and I think if we were ever to offer a print copy of the handbook, this is a good cover design.  The only feedback I can provide is that it looks too professional for void, as most of our graphical assets are slightly cobbled together.

**Comment by Vaelatern** [comment]
I personally love it. What license is the work under? Is there source?

**Comment by ericonr** [comment]
Hi! I think having a cover for the handbook is a very neat idea! I think it could fit with the design of the website a bit more. Do you think it could be done on a white background with sans-serif fonts? I'm mostly brainstorming here

And yes, having source for it would be awesome, since it allows us to update the text fields at need :D

**Comment by argosatcore** [comment]
Hi, glad you liked it! Sure, I can tweak it to be more in sync with the Void website. Do you happen to know the name of the fonts used on the website? I will make some changes and after that I will post the changes here as well as the files that contain the design. As of now, all the design was made using free software and open type fonts (Librecaslon Display and Librecaslon Text). As for the license, it doesn't have any that forbids its reproduction or modification. It is open to the public domain and may be used for any purpose. I guess the MIT license would fit this description.

**Comment by ericonr** [comment]
Possibly the fonts in https://github.com/void-linux/void-linux.github.io/tree/master/assets/fonts, definitely specified somewhere in https://github.com/void-linux/void-linux.github.io/ . I don't think we need to use the same exact font, though.

If you'd like to use the same one, this repo already uses a Creative Commons license which might fit, https://github.com/void-linux/void-docs/blob/master/LICENSE

**Comment by argosatcore** [comment]
Alright, I will take a look into it.

Sure, that license is fine by me.

**Comment by argosatcore** [comment]
This is the modified version. The san serif font's name is Liberation San Serif. I also included darker variants in the .svg file.This was entirely done using inkscape.

![Void Handbook Cover Sans](https://user-images.githubusercontent.com/64110504/90717640-4975f000-e26d-11ea-98c0-4982213a9333.png)

**Comment by argosatcore** [comment]
Oops, made a mistake will uploading the new cover and accidentally closed the issue. Anyways, here it is. It was done entirely with Inkscape. The name of the chosen font is Liberation Sans. GitHub doesn't seem to support the attachment of .svg files though this comments. Do you have an email where I can send the file?

![Void Handbook Cover Sans](https://user-images.githubusercontent.com/64110504/90717885-e042ac80-e26d-11ea-8ca1-225120cae228.png)

**Comment by Vaelatern** [comment]
Can you upload the svgs to, e.g., catbox.moe, and share the link here?

**Comment by argosatcore** [comment]
Done! Here is the link: https://files.catbox.moe/esyich.svg

**Comment by ericonr** [comment]
The cover has been added, thank you!
