### ISSUE TITLE
Add policy for changing page names

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-docs#482]
Since we want people to link to the handbook, and these links might be there for a long time, there's a chance an update to the docs would completely break the link. Instead of having to keep page names that we feel should be changed, we can use the feature described here (and in the attached PR) https://github.com/rust-lang/mdBook/issues/430 to implement proper redirection. Then, most changes to file names should also lead to an addition to the redirection table. This information should also be added to the style guide.

I can go through the git log and try and add any previously deleted pages to the redirection as well. (help wanted here, if anyone wants to make their own contribution)

**Comment by flexibeast** [comment]
@ericonr: With #487 now merged, is there anything else to be done here, or can i close this?

**Comment by ericonr** [comment]
I'd like to leave this open until Hacktoberfest, if anyone wants to give it us a hand and link some relevant old pages. What do you think?

**Comment by flexibeast** [comment]
Okay, sure.
