### ISSUE TITLE
config/xorg: Session and seat management documentation

### ISSUE THREAD

**Issue by nilium** [void-linux/void-docs#49]
**Source:** [config/xorg/index.md](https://github.com/void-linux/void-docs/blob/master/src/config/xorg/index.md)

This needs to be written by someone with knowledge of the subject, and it's not clear what needs to be covered in the first place. Attempts so far have filled out bits of the documentation (such as #38) but topics like using dbus-launch, ConsoleKit2, elogind, and other programs / services probably merits enough depth so that it's clear to users what the right thing to do is.

It'd also help to collect examples of previous questions (from reddit, the mailing list, IRC, etc.) and their solutions (when available) to figure out what troubleshooting problems come up.

**Comment by bobertlo** [comment]
Upon learning for the first time about the interconnected nature of dbus/bluetoothd/ConsoleKit/PulseAudio/PolicyKit/etc, I agree much more these should be documented... grudgingly.

I am starting to wonder though, if there should be a separate section documenting some sort of compatibility layer with Desktop Linux(™). I'm not being facetious. I have a couple machines I could test the 'flavor images' on, but I have no good idea how we can support these things from the base image gracefully.

I'm going to now go nuke all of this software I've tried to test off my EDC ThinkPad, bbl.

**Comment by ericonr** [comment]
We should at least remove ConsoleKit2 from there, as it seems to have been mostly superseded by elogind, and isn't update anymore. I opened an issue to remove it completely from packages here https://github.com/void-linux/void-packages/issues/20577, if it is I can try and rewrite a bit this one.

@bobertlo What do you think about splitting up session management into its own subject at the same level as Xorg and Wayland? It pertains to both of them (and to a tty session too, as a matter of fact), not only to Xorg.

**Comment by bobertlo** [comment]
@ericonr Definite yes on ConsoleKit2. It's actually removed from the templates repo, just still on the package server.

For moving the page, let's think about that. Maybe we could put that section and xorg under graphics? Or it might fit better in a 'Desktop Environments' section later? I think it would be clearer as a sub section vs just 'Session Management' alone. That's kind of silly reasoning but IMO true :)

**Comment by ericonr** [comment]
@bobertlo yeah, I noticed the removal. Seems there's a fix on the way to remove the actual package.

I get what you mean. Perhaps Session Management would fit better under Desktop Environments (in the sense that DEs are the way one interacts with their system). Then Xorg and Wayland could go under DE as well, being the ways a system can present a DE. Then perhaps Graphics could be under that as well, because they are what enables Xorg and Wayland to actually work?

For a better title, perhaps:

* Graphical Session
    * Xorg
    * Wayland
    * Session Management
    * Graphics drivers

**Comment by ericonr** [comment]
@nilium @bobertlo do you think we can close this one?

**Comment by ericonr** [comment]
We didn't get into polkit either... And I realized I didn't mention that `dbus` needs to be active for elogind [here](https://docs.voidlinux.org/config/graphical-session/session-management.html). We should probably include that, right?

**Comment by flexibeast** [comment]
@ericonr: Yes, i think that page should note that the `dbus` service needs to be enabled.

**Comment by ericonr** [comment]
@flexibeast #263 documents that requirement c:

I should remove WIP from it, btw.

**Comment by flexibeast** [comment]
@ericonr: Oh yes, sorry! So given what you said about removing 'WIP' from #263, do you think it might be ready for merging?

**Comment by ericonr** [comment]
@flexibeast after a final review, yes.

**Comment by flexibeast** [comment]
@ericonr: Will #263 close this? If so, the "help wanted" label can be removed.

**Comment by flexibeast** [comment]
@ericonr: With #263 now merged, can this issue be closed?

**Comment by flexibeast** [comment]
#263 has now been merged, so by ok from @ericonr, i'm closing this.
