### ISSUE TITLE
Create print versions of Handbook PDFs

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-docs#501]
As requested by @the-maldridge. The print versions should have all hyperlinks removed, and references to external links should have the external link presented as a footnote.

**Comment by NateDolny** [comment]
Hi I'm new and excited to contribute to the void community! @flexibeast I would like to start on this #501 also I should be following this: https://github.com/void-linux/void-docs/blob/master/CONTRIBUTING.md for the pdf, correct?

**Comment by Vaelatern** [comment]
Don't we already kinda have this?

**Comment by NateDolny** [comment]
There is an option for printing the handbook yes, however it does not remove the hyperlinks or external links I don't believe.

**Comment by NateDolny** [comment]
Apologies I believe @Vaelatern you are correct there seems to already be a handbook.pdf someone created. 

https://github.com/void-linux/void-docs/issues/407#issuecomment-664748624

**Comment by classabbyamp** [comment]
the void-docs package contains a LaTeX pdf of the docs yes

**Comment by Vaelatern** [comment]
There could be useful work in getting this to be easier to generate.

**Comment by classabbyamp** [comment]
it's qll generated by res/build.sh, but there could be some improvements in md -> LaTeX conversion yes.

**Comment by classabbyamp** [comment]
@NateDolny if you see some improvements to this that could be made, please PR them :)

**Comment by NateDolny** [comment]
@classabbyamp will do, thanks! 😃
