### ISSUE TITLE
iwd: mention openresolv

### ISSUE THREAD

**Issue by st3r4g** [void-linux/void-docs#525]
imho the `iwd` page should add something about the possibility to `EnableNetworkConfiguration=true` and mention that upstream defaults to `NameResolvingService=systemd` which is not good on void. One should install `openresolv` and change the setting to `resolvconf`. I wonder if the default can be changed at build time.

**Comment by Johnnynator** [comment]
There is no build option, but it is easy to patch
```diff
--- src/resolve.c	2020-09-05 09:43:41.000000000 +0200
+++ -	2020-10-27 20:27:39.193991880 +0100
@@ -554,7 +554,7 @@
 			l_warn("[General].dns_resolve_method is deprecated, "
 				"use [Network].NameResolvingService");
 		else /* Default to systemd-resolved service. */
-			method_name = "systemd";
+			method_name = "resolvconf";
 	}
 
 	for (i = 0; resolve_method_ops_list[i].name; i++) {
```

**Comment by ericonr** [comment]
That patch was added to IWD in https://github.com/void-linux/void-packages/commit/34d00472f9e7710bf909d4f6f4040fe2056fe66f
