### ISSUE TITLE
Removing location for tor mirrors

### ISSUE THREAD

**Issue by qontinuum-dev** [void-linux/void-docs#569]
Hi,
As tor is an anonymizing network that do its job by routing traffic on several locations in the world, there is no purpose to write the location of the tor mirrors.
Can this information be removed from the tor.md file?

**Comment by ericonr** [comment]
I don't think it's necessary to remove it, but if you wish to leave it unspecified in #568, it should be ok.

**Comment by qontinuum-dev** [comment]
Done thank you
