### ISSUE TITLE
CUPS pages overlap

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-docs#57]
Looking at the PR #41 it seems that the CUPS pages (config/install) are overlapping. I don't think that all of this information belongs on one page, but restructuring this section would be very helpful. There seems to be installation and configuration information mixed between both pages and, in some cases, duplicated.

**Comment by CameronNemo** [comment]
It could go on one page maybe. Indeed it could use a little restructuring. Currently the model is stage 1 install everything you might want, stage 2 configure what you installed. Probably not the best way to go about it.

**Comment by bobertlo** [comment]
I agree, I could have qualified that statement. I didn't mean these necessarily need to be merged into one page.

**Comment by bobertlo** [comment]
Closed by #64
