### ISSUE TITLE
Full Disk Encryption: No mention of resolv.conf

### ISSUE THREAD

**Issue by ghost** [void-linux/void-docs#571]
In the [Full Disk Encryption guide](https://docs.voidlinux.org/installation/guides/fde.html), resolv.conf is described.
In fact, I need to do `cp /etc/resolv.conf /mnt/etc/`.

**Comment by ericonr** [comment]
I could see it suggested in the general chroot guide, maybe. The FDE guide shouldn't get new details, IMO.

**Comment by goc980** [comment]
> I could see it suggested in the general chroot guide, maybe. The FDE guide shouldn't get new details, IMO.

The Void installation guide is very confusing. I want it to be as easy to understand as Arch.

**Comment by ericonr** [comment]
Could you explain the issues you are seeing?

**Comment by abenson** [comment]
They've since left GitHub.
