### ISSUE TITLE
Documentation leads you down the garden  path and leaves you hanging

### ISSUE THREAD

**Issue by mark4th** [void-linux/void-docs#592]
https://docs.voidlinux.org/installation/guides/fde.html

I always install with an encrypted / partiton, if i cannot encrypt / i move on to a different distribution.  This documentation starts with instructions to format the entire drive as luks1, then create logical volumes and format and mount them
ONLY THEN does it tell you you need an EFI partiton which ... newp... theres no space for now because we just formatted the entire drive as luks1
The documentation should START with 1) create EFI partiton and 2) create linux partiton... format  efi partiton, encrypt second partiton.... and continue from there.

**Comment by paper42** [comment]
Are you sure? The first part is true for MBR systems without UEFI, the second part is true for systems with UEFI. I think it's clearly distinguishable.

> Create a single physical partition on the disk using cfdisk, marking it bootable. **For an MBR system, the partition layout should look like the following.**
> 
> > ```
> > # fdisk -l /dev/sda
> > Disk /dev/sda: 48 GiB, 51539607552 bytes, 100663296 sectors
> > Units: sectors of 1 * 512 = 512 bytes
> > Sector size (logical/physical): 512 bytes / 512 bytes
> > I/O size (minimum/optimal): 512 bytes / 512 bytes
> > Disklabel type: dos
> > Disk identifier: 0x4d532059
> >
> > Device     Boot Start       End   Sectors Size Id Type
> > /dev/sda1  *     2048 100663295 100661248  48G 83 Linux
> > ```
>
> UEFI systems will need the disk to have a GPT disklabel and an EFI system partition. The required size for this may vary depending on needs, but 100M should be enough for most cases. **For an EFI system, the partition layout should look like the following.**
> 
> > ```
> > # fdisk -l /dev/sda
> > Disk /dev/sda: 48 GiB, 51539607552 bytes, 100663296 sectors
> > Units: sectors of 1 * 512 = 512 bytes
> > Sector size (logical/physical): 512 bytes / 512 bytes
> > I/O size (minimum/optimal): 512 bytes / 512 bytes
> > Disklabel type: gpt
> > Disk identifier: EE4F2A1A-8E7F-48CA-B3D0-BD7A01F6D8A0
> >
> > Device      Start       End   Sectors  Size Type
> > /dev/sda1    2048    264191    262144  128M EFI System
> > /dev/sda2  264192 100663262 100399071 47.9G Linux filesystem
> > ```

The first part is clearly meant "For an MBR system" (systems without EFI), the second part is "For an EFI system". I would maybe argue that the EFI part should be higher than the old MBR part, because most people are using systems with UEFI nowadays, but that's a very very small issue. Am I looking at the wrong part of the guide? Could you quote the part you are referring to?
