### ISSUE TITLE
Get jack pipewire to work properly on musl

### ISSUE THREAD

**Issue by notthewave** [void-linux/void-docs#603]
Currently, following the void docs on pipewire does not lead to satisfactory results. There is a section in the alpine repo which works. I know the docs are against duplication of information, but this _**should at least be clarified.**_ Spent quite some time finding this out. 
https://wiki.alpinelinux.org/wiki/PipeWire

The solution proposed in the docs does not make cadence work correctly. But the one in alpine wiki does.

**Comment by notthewave** [comment]
```
# ln -sf /usr/lib/pipewire-0.3/jack/libjackserver.so.0 /usr/lib/libjackserver.so.0
# ln -sf /usr/lib/pipewire-0.3/jack/libjacknet.so.0 /usr/lib/libjacknet.so.0
# ln -sf /usr/lib/pipewire-0.3/jack/libjack.so.0 /usr/lib/libjack.so.0
```

**Comment by ericonr** [comment]
I don't feel comfortable recommending things that will be flagged by `xbps-pkgdb`.

**Comment by Vaelatern** [comment]
Maybe we can do something with alternatives?

Why does this work on glibc and not musl, difference in loading?

**Comment by st3r4g** [comment]
I thought `pw-jack` worked on musl. Uses `LD_LIBRARY_PATH`. Or are you referring to the `ld.so` override?

**Comment by st3r4g** [comment]
```
LD_LIBRARY_PATH='/usr/${LIB}/pipewire-0.3/jack'"${LD_LIBRARY_PATH+":$LD_LIBRARY_PATH"}"
```
Ah, maybe this is why. Try to replace `${LIB}` with `lib`.

**Comment by st3r4g** [comment]
@ericonr I think we can close this as `pw-jack` now works on musl

**Comment by ericonr** [comment]
Indeed, thanks!
