### ISSUE TITLE
Missing warning/disclaimer about automatic unlock of full disk encryption

### ISSUE THREAD

**Issue by Costava** [void-linux/void-docs#604]
The [Full Disk Encryption]( https://docs.voidlinux.org/installation/guides/fde.html ) page includes instructions for automatically unlocking the encrypted volume at boot:

> And now to avoid having to enter the password twice on boot, a key will be configured to automatically unlock the encrypted volume on boot.

This automatic unlocking seems to defeat a lot of the purpose of full disk encryption -- any person with access/possession of the drive can decrypt the drive without needing to know any secret?

**It seems like there should be a warning/disclaimer for this part of the page.**

---

Am I misunderstanding what this part of the FDE setup does? Other places online have matching/analogous instructions and plainly state that the full disk encryption becomes no longer useful.

> Warning: following this guide will render disk encryption useless. You will be storing your encryption key, plain-text, in the unencrypted part of the disk!

at https://dradisframework.com/support/guides/customization/auto-unlock-luks-encrypted-drive.html

> Motivation
>
> You have Luks  encrypted root partition,  and want deactivate it for a while,

at https://bbs.archlinux.org/viewtopic.php?id=254012

> Do you mean decrypt without entering a passphrase? If the boot process could do that, then the keys necessary to decrypt the volume would need to be on the system somewhere accessible during boot. How would you expect that to protect you from data theft?

at https://askubuntu.com/questions/59487/how-to-configure-lvm-luks-to-autodecrypt-partition

**Comment by abenson** [comment]
The key is in a file, in the ramdisk, on the encrypted disk.  GRUB unlocks the disk with a secret passphrase and loads the ramdisk.

The key is not exposed until you enter the passphrase.

**Comment by Costava** [comment]
Ah. GRUB still prompts for the passphrase. I assumed the worst and did not look into it properly. Thank you.

---

After your response, I went through the steps and do see only the one passphrase prompt from GRUB.
I did `cryptsetup luksRemoveKey`, removed `install_items+=" /boot/volume.key /etc/crypttab "` from `/etc/dracut.conf.d/10-crypt.conf`, and on next boot, saw both prompts.
