### ISSUE TITLE
Network manager should be installed by default

### ISSUE THREAD

**Issue by dankmemermusic** [void-linux/void-docs#674]
*Before opening a request, please be sure to check [what content is suitable for the Handbook](https://docs.voidlinux.org/about/about-this-handbook.html).*

We prioritize requests for information specific to Void, and try to avoid duplicating information already available elsewhere (e.g. on the Arch wiki).

I find it impossible to connect to wifi with wpa-supplicant. so network manager [tui](https://man.voidlinux.org/nmtui.1) should be installed by default

**Comment by Vaelatern** [comment]
Not documentation related. Also Void won't do this. Feel free to use the text interface given in void-installer for installation media, or install whatever you like on your own systems.
