### ISSUE TITLE
Create mirror Pikeville, Kentucky, USA

### ISSUE THREAD

**Issue by sandyrivernet** [void-linux/void-docs#706]
Sponsor Name: Skynet Communications of Kentucky
  Location: Pikeville, Kentucky
  Bandwidth: 2Gb/s 
Admin Contact: help@sandyriver.on.spiceworks.com (Creates ticket)
Primary Admin Email: clinton.strouth@sandyriver.net

The mirror can be accessed via the following URLs:

 HTTP: mirror2.sandyriver.net/pub/voidlinux/
 HTTPS: mirror2.sandyriver.net/pub/voidlinux/
RSYNC: mirror2.sandyriver.net/pub/voidlinux/

IPv6 connectivity [yes v4+v6/yes v6 only/no]: no (working on ipv6) 

There is a limit on concurrent connections [amount/no]: no 

Additional comments:
Mirror is updated every four hours from 
rsync://alpha.de.repo.voidlinux.org/voidmirror/
Site can be used by other mirror sites to update from.

**Comment by classabbyamp** [comment]
would recommend changing the sync source to `rsync://repo-default.voidlinux.org/voidmirror/`, it's the same box but `alpha.de.repo` is an old dns name for it

**Comment by classabbyamp** [comment]
closed by eff83cefe50820b07624155d5a045235b68d5b7e
