### ISSUE TITLE
Root on ZFS: potentially missing host ID generation step

### ISSUE THREAD

**Issue by chloris-pale-green** [void-linux/void-docs#736]
Recently, I've performed a root-on-ZFS install of Void with a separate `boot` partition and GRUB bootloader. I followed our [official guide](https://docs.voidlinux.org/installation/guides/zfs.html).

I've noticed that the system does not boot past the `dracut` prompt sometimes (presumably after kernel upgrades), displaying error about `zroot` zpool being imported to other systems and that I should export it from other systems first. The action needed to boot is suggested and easily performed: force import the zpool. But this should not happen in the first place.

I believe this is a consequence of a missing step in the guide for generating host ID. [ZFSBootMenu guide for Void](https://docs.zfsbootmenu.org/en/latest/guides/void-linux/uefi.html) includes a step for generating host ID in the live environment itself, later followed by copying the host ID to the physical machine.

I think that the official Void guide for root on ZFS could benefit from including the `zgenhostid` command.

Though even now `zpool status` returns the following for `zroot`:
```text
  pool: zroot
 state: ONLINE
status: Mismatch between pool hostid and system hostid on imported pool.
        This pool was previously imported into a system with a different hostid,
        and then was verbatim imported into this system.
action: Export this pool on all systems on which it is imported.
        Then import it to correct the mismatch.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-EY
config:

        NAME                                             STATE     READ WRITE CKSUM
        zroot                                            ONLINE       0     0     0
          ata-Crucial_CT250MX200SSD1_15230FBB7979-part4  ONLINE       0     0     0
```

I can not find the link to a "solution" on StackOverflow, but it included generating host ID, enabling the multiple import property on the zpool, and then disabling it again, stating that it would update its import host ID.

Anyone has more experience with ZFS? I'd like to hear your opinion about the suggestion.

**Comment by ahesford** [comment]
The use of `hostid` in ZFS has cause a lot of people a lot of problems and, on balance, I believe its presence is a detriment to the ZFS experience. ZFSBootMenu works around this by trying very hard to adopt the right `hostid` when it has difficulty importing pools, then forcing this via the `spl.spl_hostid` kernel command-line argument on any environment that it boots. In the absence of forcing a value via the SPL module parameter, there remain several `hostid` pitfalls that can ensare users even when `/etc/hostid` exists and is included in the initramfs. With dracut, `/etc/hostid` is *only* used in "host-only" mode, so if you aren't building host-only images, the file will be ignored and you'll have the same problems. The `spl_hostid` kernel command-line parameter is recognized by dracut as a "weaker" version of the module parameter `spl.spl_hostid` and will trigger dracut to write its own `/etc/hostid` with the contents of the variable before attempting to import pool. With mkinitcpio, the file is always included and honored by default. There is no support for the `spl_hostid` argument in mkinitcpio, so the only option for overriding an existing (or missing) `/etc/hostid` in mkinitcpio images is the hard `spl.spl_hostid` parameter.

I suspect that you've created an `/etc/hostid` file after the fact. ZFS always falls back to a zero `hostid` when the SPL module parameter is unset and `/etc/hostid` doesn't exist. You can probably achieve reliable imports by just removing `/etc/hostid` on your system and from your initramfs image and letting the fallback take effect.

**Comment by chloris-pale-green** [comment]
@ahesford, thank you very much for your thorough explanation! Consequently, I will close this issue.

I leave it to discretion of all well-versed people reading this whether it would be beneficial to shortly mention `hostid` in the root-on-ZFS docs or not.
