### ISSUE TITLE
table of contents navigation is not optimal

### ISSUE THREAD

**Issue by sam6816** [void-linux/void-docs#778]
The (toggle-able) TOC "panel" on the left is very **long**, always **expanded** and is stuck to the contents on the right when **scrolling**. It is really bad when you want to get an overview of a section or subsection, it always jumps away. 

Thing is, I wanted to figure out how to turn section _4. XBPS Package Manager_ into a "Maintenance" section, without even changing that much (issue #616). But with such a navigation I'm not sure. As it is now, I'd say the whole section _3. Configuration_ has to be split off, otherwise even the "general package management" list of xbps-commands is quite buried.  

A lot of important info is there in section 4, but hidden at the end and not presented nicely. This is also TOC's fault and the stone-age way it behaves. Can this be changed, technically?

**Comment by classabbyamp** [comment]
it's fairly baked into mdbook but it might be changeable with css

**Comment by sam6816** [comment]
OK I just have to use the arrow keys for linear navigation in these downstairs chapters, and not even think about scrolling back down. Annoying (IMO) for everything like _3.11 Kernel_ and below, but superficial in the end. That said, looks like it is up to me to close this, technically. Thx for the short but informative reply.
