### ISSUE TITLE
Void-installer - Configured partitions not shown in filesystem

### ISSUE THREAD

**Issue by naoNao89** [void-linux/void-docs#797]
After running `cfdisk` or `fdisk` to configure partitions during the Void Linux installation process, the configured partitions are not showing up in the filesystem. The only drive visible is the USB drive used for booting the installer.

This appears to be an issue with the Void-installer, as the partitions that were set up in the previous step are not being properly recognized or mounted in the final filesystem.

## Steps to Reproduce:

1. Boot into the Void Linux installer
2. Choose Partition
3. Complete the installation process
4. Observe that the configured partitions are not visible in the final filesystem - only the USB boot drive is shown

**Comment by classabbyamp** [comment]
did you [write] the partition table in cfdisk?

**Comment by naoNao89** [comment]
Partitioning a Disk Using fdisk in Linux
1. Identify the disk:
   ```
   sudo lsblk
   ```
   This will list all the block devices connected to your system. Identify the disk you want to partition, e.g., `/dev/sda` or `/dev/nvme0n1`.

2. Enter the `fdisk` interactive prompt:
   ```
   sudo fdisk /dev/[DEVICE]
   ```
   Replace `[DEVICE]` with the disk you want to work with, e.g., `/dev/sda`.

3. Create a new partition table:
   Inside the `fdisk` prompt, type:
   ```
   o
   ```
   This will create a new empty DOS partition table.

4. Create a new partition:
   Inside the `fdisk` prompt, type:
   ```
   n
   ```
   Follow the prompts to specify the partition type (primary or extended), partition number, and the start and end sectors for the new partition.

5. Set the partition type (optional):
   Inside the `fdisk` prompt, type:
   ```
   t
   ```
   Then select the appropriate partition type code, e.g., `83` for a Linux native partition or `82` for a Linux swap partition.

6. Make the partition bootable (optional):
   Inside the `fdisk` prompt, type:
   ```
   a
   ```
   Then select the partition number you want to make bootable.

7. Write the changes and exit:
   Inside the `fdisk` prompt, type:
   ```
   w
   ```
   This will write the changes to the disk and exit `fdisk`.

8. Format the new partition:
   ```
   sudo mkfs.ext4 /dev/[PARTITION]
   ```
   Replace `[PARTITION]` with the name of the new partition you created, e.g., `/dev/sda1`.

Remember to replace `[DEVICE]` and `[PARTITION]` with the appropriate names for your system. Also, always double-check your work and back up any important data before making changes to the partition table.

**Comment by naoNao89** [comment]
> did you [write] the partition table in cfdisk?

Thanks for the tip on the GitHub issue. Your suggestion about cfdisk was exactly what I needed to fix the problem. As a newbie, I really appreciate you taking the time to provide that helpful feedback. I knew how to fix this bug and I also created an issue for others who may have encountered it.
