### ISSUE TITLE
Need and automated style guide and formatter

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-docs#8]
This repo needs an automatic style check and ideally an auto-formatter.  Now taking suggestions.

**Comment by bobertlo** [comment]
https://github.com/markdownlint/markdownlint looks promising as far as style checking.

**Comment by bobertlo** [comment]
`pandoc -t markdown --atx-headers` seems to do a decent job autoformatting also.

**Comment by bobertlo** [comment]
I ran the above pandoc command recursively on my isntallguide branch without squashing the commit.

I just used:
```
#!/bin/sh                                                                       
                                                                                
for file in $@                                                                  
do                                                                              
    pandoc -t markdown --atx-headers "$1" > "$1.lint"                           
    mv "$1.lint" "$1"                                                           
done
```

And executed it on all markdown files. It may not be exactly what you were thinking, but maybe a good start?

**Comment by bobertlo** [comment]
See #9 as a possible suggestion for autoformatting.

**Comment by bobertlo** [comment]
I started working on a go program that, so far, can traverse markdown trees. With some restrictions on the acceptable input in the context of an mdbook, it would be feasible to create an auto-formatter which can catch violations of some simple rules aswell. I'm not sure if this is what you mean?

**Comment by the-maldridge** [comment]
That's basically exactly what I mean.  The tricky bit is that it needs to handle tables, and I have some specific requests around how it handles links.  How developed is your program?

**Comment by the-maldridge** [comment]
Waiting on https://github.com/bobertlo/vmd

**Comment by bobertlo** [comment]
I fixed the newline issue and did push to master, since the CI will more than likely fail without the auto-formatter.

I staged void package and would like to add documentation about the autoformatter, so contributors don't have to `gimme` a go install, but that should wait until I finish the frontend at least. I will stay in touch and *not break anything*. I want to do some refactoring *after* writing tests. Other than images I do not see any features I would like to add without some sort of a consensus.

If people feel strongly about footnoted links, there is a possibility of collecting duplicate links and emitting them at the end of the file. That style issue is above my paygrade but I would be happy to look into it.

**Comment by the-maldridge** [comment]
vmdfmt has been adopted as the official formatting tool.

**Comment by unix-lover** [comment]
I know this is closed as being solved with vmdfmt, but I might add the suggestion that similar tools exist (even in Go) that have already gained some maturity. Check these out:

- [markdownfmt](https://github.com/shurcooL/markdownfmt) (Go, seems to be the most popular)
- [mdfmt](https://github.com/moorereason/mdfmt) (also Go)
- [tidy-markdown](https://github.com/slang800/tidy-markdown) (CoffeeScript)

I do have a preference for Go but there are probably many other options too.

Tools like this are obviously built around a certain style guide, so we'd have to see how much they conform to the style we choose, but the two first ones I listed, for example, are licensed permissively with the MIT license so we could even just fork it and tweak it to our needs. I think it would be easier than trying to build something from scratch.
