### ISSUE TITLE
Add hint for font configuration under Wayland section

### ISSUE THREAD

**Issue by kardwen** [void-linux/void-docs#802]
I installed River while following the article on [Wayland](https://docs.voidlinux.org/config/graphical-session/wayland.html) and had the issue that I could not start any terminal emulator with the keybinding in my init script (I tried out alacritty and food). This issue arised because I had not configured a font, I think it would be useful to add a reference to [Fonts](https://docs.voidlinux.org/config/graphical-session/fonts.html) under Installation or Configuration in this article.

**Comment by classabbyamp** [comment]
done in #810
