### ISSUE TITLE
Mention void-infect

### ISSUE THREAD

**Issue by Jipok** [void-linux/void-docs#819]
https://github.com/Jipok/void-infect

![изображение](https://github.com/user-attachments/assets/8cdc94ee-13c2-47ad-8ea4-b1054077f2ae)

I didn't really want to write this script. But void is a very convenient system for servers. And every time installing it from iso via vnc was painful. And I couldn't find any solutions. So the inconvenience overcame laziness and this script appeared. It seems to me that I have completely solved this problem. At least I tried and tested it a lot in different situations so that everything would work for people.

The only thing I didn't test was ipv6-only vps because unfortunately my hoster doesn't have this option.

**Comment by ahesford** [comment]
We do not recommend third-party installers.

**Comment by Jipok** [comment]
This was a surprisingly fast response. I thought it would hang for years.

Just take control of the script. It's finished. The license allows it.
